version: '3'

services:
  scylladb-node1:
    image: scylladb/scylla-enterprise:2019.1.9
    networks:
      - scylla-net
    volumes:
      - ./data/node1:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"
  scylladb-node2:
    image: scylladb/scylla-enterprise:2019.1.9
    networks:
      - scylla-net
    volumes:
      - ./data/node2:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"
  scylladb-node3:
    image: scylladb/scylla-enterprise:2019.1.9
    networks:
      - scylla-net
    volumes:
      - ./data/node3:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"

networks:
  scylla-net:  